### ISSUE TITLE
Doesn't work with custom Rust sysroot

### ISSUE THREAD

**Issue by jdm** [cuviper/autocfg#12] opened 2019-10-10 14:58 UTC
This affects using autocfg in build setups that involve the new `-Z build-std` flag or xargo, both of which pass a `--sysroot [something]` flag when invoking rustc. The xargo case can be worked around by checking for RUSTFLAGS and passing them when probing using rustc, but I'm not sure what to do about build-std, since the sysroot doesn't appear to be exposed to build scripts at the moment.

**Comment by roblabla** [comment] 2019-10-10 15:09
#10 has a partial fix for xargo by applying the RUSTFLAGS. The problem is, it's only a partial fix because of https://github.com/cuviper/autocfg/pull/10#issuecomment-527575030.

**Comment by cuviper** [comment] 2019-10-20 21:37
Should now be fixed by #10 -> #13, published as 0.1.7.

**Closed as completed by cuviper** 2019-10-20 21:37 UTC

**Comment by cuviper** [comment] 2019-10-20 21:40
Well, at least `RUSTFLAGS` is fixed -- I don't know about `-Z build-std`, but I guess we can reopen the issue if that's needed. Given that `-Z` options are still unstable, maybe we can influence its final design in some way to make `autocfg` support feasible.
